### ISSUE TITLE
circular reference warnings when used with Rails 4.2.7 and ruby-2.3.1

### ISSUE THREAD

**Issue by mid9commander** [hjhart/rspec-parts#1]
lib/rspec/parts/file_list.rb#36

/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-parts-0.2.0/lib/rspec/parts/file_list.rb:36: warning: circular argument reference - glob
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-parts-0.2.0/lib/rspec/parts/file_list.rb:36: warning: circular argument reference - groups
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-parts-0.2.0/lib/rspec/parts/file_list.rb:36: warning: circular argument reference - part

http://blog.vrinek.io/2015/01/15/ruby-2-2/

**Comment by hjhart** [comment]
I'm happy to take PRs on this issue. I might not get around to fixing this for a while.
